Ft payl initial payload proc functions
USST-RADSAT-SK/software-and-command pull request #11
Opened 2020-02-22 23:25 UTC by tyrelkostyk

Initial creation of payload processing functions. Contains but one function that rapidly polls and aquires data from each of the 8 sensors on both dosimeter boards. Relies on external functions from housekeeping team to send/recieve i2c commands/data, and to store payload data in memory.

2020-02-23 02:47 UTC, MackenzieStanger requested changes

2020-02-23 02:47 UTC, MackenzieStanger commented on payload-processing/payload_processing.h
> +#define DOSIMETER_REFERENCE_VOLTAGE	(float) 3.30;
```suggestion
#define DOSIMETER_REFERENCE_VOLTAGE	( (float) 3.30 )
```
Macros don't need semi colons. I would also wrap it in brackets just to be safe

2020-02-23 03:02 UTC, MackenzieStanger commented on payload-processing/payload_processing.h
> +#define DOSIMETER_REFERENCE_VOLTAGE	(float) 3.30;
Also should probably add the documentation comments in if you have time. Other than that the code looks good to me

2020-02-23 19:58 UTC, rarohel reviewed
I'm confused by the conversion bytes, is the "high" byte supposed to be the top 8 bits and the "low" byte the bottom 8? It just seems a little confusing, perhaps some more documentation might be helpful.

2020-02-25 15:58 UTC, rarohel approved these changes
Awesome, looks good!

2020-03-06 23:12 UTC, MackenzieStanger approved these changes

2020-04-02 06:40 UTC, merged