Added "Test" build config
USST-RADSAT-SK/software-and-command pull request #161
Opened 2021-12-29 23:56 UTC by tyrelkostyk

Added the `Test` build configuration, and set the necessary project settings to make it all work. Also added a basic Test Suite framework; not sure how much it'll be used or if it'll always look like that, but it's one way of doing it.

**To test and approve this PR:**
1. Close Eclipse
2. Checkout the branch `admin/test-build-config`
3. Start Eclipse
4. Build the Test configuration (hit the arrow next to the hammer icon, and select `Test` instead of `Debug`)
5. There should be no build errors
6. Go to `main.c` -> Lines wrapped in `#ifdef TEST` should NOT be greyed out (e.g. lines 21-23 and 86-92)

2022-01-10 19:39 UTC, ChrisAmaya commented
I followed your steps but both #ifdef TEST is grayed out. I tried to mess around with the settings and what worked for me is I went into the properties tab -> C/C++ General -> Indexer -> and changed the bottom drop-down to test. 

The problem I ran into while doing this was that I cannot change back to different builds using the dropdown menu by the build hammer icon I would have to change the configuration via that path mentioned before (C/C++ -> Indexer -> ...). 

I am unsure what they mean by "indexer" in the first place but it does seem to help with the configuration symbols

2022-01-10 19:42 UTC, ChrisAmaya requested changes
Please review my comment I left about the settings I tried to get the configuration to work

2022-01-10 19:42 UTC, ChrisAmaya commented on radsat-sk/src/main.c
> +	testSuiteRunAll();
Cool abstract idea

2022-01-20 03:38 UTC, tyrelkostyk commented
UPDATE: Fixed Addi's above issue (which I was also seeing)

1. Open Eclipse
2. Go to `Window > Preferences > C/C++ > Indexer`
3. On that page, near the middle/bottom, there will be an option: _Build Configuration for the Indexer_
    - Select **Use active build configuration**
4. Close Eclipse
5. Checkout the branch for this PR (`admin/test-build-config`) if not done already
6. Proceed to test & evaluate PR as explained in the initial PR comment above

2022-01-20 04:18 UTC, ChrisAmaya approved these changes

2022-01-20 16:42 UTC, matthew-buglass approved these changes
Looks good and works for me.

2022-01-26 22:53 UTC, merged

2022-01-26 23:01 UTC, tyrelkostyk commented
Updated the Team Training doc as well, to include the necessary steps required to change the local project settings

Link to training doc: https://www.dropbox.com/home/CubeSat/Subteams/Software%20and%20Command/Learning/Training
^ **In section 4.5.4**