Operation/initial obc implementation
USST-RADSAT-SK/software-and-command pull request #174
Opened 2022-04-14 01:56 UTC by ChrisAmaya

A fairly simple addition to the code

2022-04-14 23:16 UTC, matthew-buglass approved these changes, later dismissed

2022-05-10 05:47 UTC, TheDopplerEffects submitted a review, later dismissed

2022-05-11 22:03 UTC, tyrelkostyk requested changes, later dismissed

2022-05-11 22:03 UTC, tyrelkostyk commented on radsat-sk/operation/subsystems/RObc.c
> + * @file RObc.h
Incorrect file type

2022-05-11 22:03 UTC, tyrelkostyk commented on radsat-sk/operation/subsystems/RObc.c
> +	}
Need to report error to the Error Manager (once it's available)

2022-05-11 22:03 UTC, tyrelkostyk commented on radsat-sk/operation/subsystems/RObc.c
> +int obcTelemetry(obcTelemetry_t* obcTelemetryBuffer){
The word "buffer" doesn't make a ton of sense in this context; I would just call it "telemetry"

2022-05-11 22:03 UTC, tyrelkostyk commented on radsat-sk/operation/subsystems/RObc.c
> +
This function probably isn't necessary; we already have `WDT_startWatchdogKickTask` provided by the HAL which is supposed to start a FreeRTOS task to do all of the kicking for us. At the very least, this function should mention the existence of that HAL function.

2022-05-11 22:03 UTC, tyrelkostyk commented on radsat-sk/operation/subsystems/RObc.h
> +} obcTelemetry_t;
Incorrect style name for the struct. Proper name would be `obc_telemetry_t`

2022-05-11 22:03 UTC, tyrelkostyk commented on radsat-sk/operation/subsystems/RObc.h
> +int obcTelemetry(obcTelemetry_t* obcTelemetryBuffer);
See other commend on name of argument; would just call it `telemetry` instead

2022-05-23 18:31 UTC, ATGr8 commented on radsat-sk/operation/subsystems/RObc.c
> +int obcTelemetry(obcTelemetry_t* telemetry){
add space between ) and {

2022-05-23 18:34 UTC, ATGr8 commented on radsat-sk/operation/subsystems/RObc.h
> +
remove whitespace

2022-05-23 18:35 UTC, ATGr8 commented on radsat-sk/operation/subsystems/RObc.h
> +
remove whitespace

2022-05-23 18:35 UTC, ATGr8 commented on radsat-sk/operation/subsystems/RObc.h
> +
remove whitespace

2022-05-23 18:36 UTC, ATGr8 commented on radsat-sk/operation/subsystems/RObc.h
> +
remove whitespace

2022-05-23 18:38 UTC, ATGr8 commented
petWatchDog function is defined in .h file but not implemented in .c file

2022-06-05 02:17 UTC, ATGr8 commented on radsat-sk/operation/subsystems/RObc.c
> + * @return	Error code; 0 for success, otherwise see hal/errors.h.
remove whitespace between @return and "Error code"

2022-06-17 03:15 UTC, ATGr8 approved these changes
Looks good!

2022-06-17 22:43 UTC, merged