Framework/implement uart wrapper
USST-RADSAT-SK/software-and-command pull request #41
Opened 2021-05-18 02:40 UTC by ChrisAmaya

2021-06-08 01:47 UTC, Lars-Kish commented
Instead of using bus2_uart, should the enum UARTbus be used in RUart.c?

2021-06-08 03:46 UTC, ThomasSlotboom commented on radsat-sk/framework/wrappers/RUart.c
> +uint32_t uartBlockingRecieve(uint8_t* data, uint16_t size) {
There's a typo in this function, it's spelled receive

(i before e except after c or in weird words like weird)

2021-06-08 03:51 UTC, ThomasSlotboom requested changes

2021-06-08 03:51 UTC, tslotboom commented on radsat-sk/framework/wrappers/RUart.h
> +uint32_t UART_blockingTransmit(const uint8_t* data, uint16_t size);
The names of these function declarations don't match the names of the function definitions in the c file

2021-06-22 01:41 UTC, mpbtruong commented
Looks good! Just pending those changes as per Thomas' comments.

2021-06-22 01:42 UTC, mpbtruong approved these changes

2021-07-09 00:48 UTC, ThomasSlotboom approved these changes

2021-07-09 00:48 UTC, merged