Hotfix/err check fram init
USST-RADSAT-SK/software-and-command pull request #54
Opened 2021-10-02 02:28 UTC by ATGr8

I added an error check in FRAM_read.

2021-10-05 17:51 UTC, ChrisAmaya requested changes

2021-10-05 17:51 UTC, ChrisAmaya commented on radsat-sk/framework/fileio/RFram.c
> +	uint16_t err = FRAM_read(data, address, size);
Again, please review pointer or we can talk about how pointers work because the parameter passed into FRAM_read is not what its expecting

2021-10-05 17:51 UTC, ChrisAmaya commented on radsat-sk/framework/fileio/RFram.c
> +		}
Please review our coding standards in the README for if statements and spacing and brackets

2021-10-05 17:51 UTC, ChrisAmaya commented on radsat-sk/framework/fileio/RFram.c
>  	return FRAM_read(data, address, size);
For readability sake, wrap this in an else statement

2021-11-02 03:04 UTC, matthew-buglass requested changes
You already have the return value from the first function call. We don't need to call it again.

2021-11-03 01:40 UTC, matthew-buglass approved these changes

2021-11-03 01:43 UTC, ChrisAmaya approved these changes

2021-11-03 01:43 UTC, merged