Framework/spi
USST-RADSAT-SK/software-and-command pull request #70
Opened 2021-11-22 19:28 UTC by ATGr8

2021-11-23 02:39 UTC, matthew-buglass commented
Remember to add documentation to the C file.

2021-11-23 02:57 UTC, ATGr8 commented
> Remember to add documentation to the C file.

Thanks, I added them

2021-11-29 02:51 UTC, matthew-buglass requested changes
Looks good, except for the .vscode settings being included. But I'm not sure what our policies on that, so I'll leave the to @ChrisAmaya to decide.

2021-11-29 02:51 UTC, matthew-buglass commented on .vscode/settings.json
> +    "files.associations": {
I don't think that the IDE setting should be uploaded to the repo

2021-11-29 06:47 UTC, ChrisAmaya requested changes

2021-11-29 06:47 UTC, ChrisAmaya commented on radsat-sk/framework/wrappers/RSPI.h
> +#define BUS 0
you have 2 defines but they arent being used anywhere in your .c files

2021-11-29 06:47 UTC, ChrisAmaya commented on radsat-sk/framework/wrappers/RSPI.h
> +uint32_t spiInit();
You have no parameters in your function declaration but you have then in your .c

2021-12-25 17:10 UTC, closed without merging